version: '2'
services:
    mongodb:
        image: mongo:3.3
        ports: 
            - 27017:27017

    nodetest:
        build:
            context: .
            args:
                NEW_RELIC_LICENSE_KEY:
        links:
            - mongodb
        environment:
            NEW_RELIC_LICENSE_KEY:
        ports:
            - 3000:3000
            - 3001:3001 
        command: npm run-script docker