version: '2'
services:
    mongodb:
        image: mongo:3.3
        ports: 
            - 27017:27017

    nodetestapi:
        build:
            context: .
        image: newrelic/nodetest
        links:
            - mongodb
        environment:
            NEW_RELIC_LICENSE_KEY:
            NEW_RELIC_APP_NAME: 'Nodetest API'
        ports:
            - 3001:3001
        command: npm run api        

    nodetestweb:
        image: newrelic/nodetest
        links:
            - mongodb
            - nodetestapi
        environment:
            NEW_RELIC_LICENSE_KEY:
            NEW_RELIC_APP_NAME: 'Nodetest Express Web'
        ports:
            - 3000:3000
        command: npm run web

    nodetestload:
        image: newrelic/nodetest
        links:
            - nodetestweb
        command: npm run load
        

    